### PR TITLE
Fix for ids not getting unregistered when unacessed nodes die

### LINKED ISSUE #1112: Nested nodes with identifiers are not detached and not removed from the identifiers cache
Works good:

```
const mock1 = [{ id: '1', name: 'Kate' }, { id: '2', name: 'John' }]
const mock2 = [{ id: '3', name: 'Andrew' }, { id: '2', name: 'John' }]

const Entity = types.model({
  id: types.identifier,
  name: types.string
})

const Store = types.model({
  list: types.optional(types.array(Entity), []),
  selectedId: 2
})
.views(self => ({
  get selectedEntity() {
    return resolveIdentifier(Entity, self, self.selectedId)
  }
}))

const store = Store.create()
unprotect(store);

(async function () {
    store.list.replace(mock1)
    await delay(500)
    store.list.replace(mock2)
  })()

// Render selectedEntity
```

Throws an error:

```
const mock1 = [{ id: '1', name: 'Kate' }, { id: '2', name: 'John' }]
const mock2 = [{ id: '3', name: 'Andrew' }, { id: '2', name: 'John' }]

const mock1_2 = mock1.map((i, index) => ({ text: `Text${index}`, entity: i }))
const mock2_2 = mock1.map((i, index) => ({ text: `Text${index}`, entity: i }))

const Entity = types.model({
  id: types.identifier,
  name: types.string
})

const Wrapper = types.model({
  text: types.string,
  entity: Entity,
})

const Store = types.model({
  list: types.optional(types.array(Wrapper), []),
  selectedId: 2
})
.views(self => ({
  get selectedEntity() {
    return resolveIdentifier(Entity, self, self.selectedId)
  }
}))

const store = Store.create()
unprotect(store);

(async function () {
    store.list.replace(mock1_2)
    await delay(500)
    store.list.replace(mock2_2)
  })()

// Render selectedEntity
```

**[mobx-state-tree] Cannot resolve a reference to type 'AnonymousModel' with id: '2' unambigously, there are multiple candidates: /list/1/entity, /list/1/entity**

I tried to call the "detach" method for each existing "Wrapper" entity manually before replacing of the array items, and it works, but i think it's not good idea, because it's difficult to control the all array modifications. For example, someone can call the "applySnapshot" method on any parent node and this fix wouldn't work.

### PR DESCRIPTION
**Pull request by xaviergonz**
Fixes #1112

### CODE REVIEW

**Comment by xaviergonz** [comment]
I think storedValue only becomes a state tree node once it is accessed

**Comment by k-g-a** [comment]
What I meant by the previous question is: should we really check for ```storedValue``` at all, as after [1082](https://github.com/mobxjs/mobx-state-tree/pull/1082) we do not rely on it durning node's death?
The thing that stopped me from removal of this check is failing "it should trigger lifecycle hooks" test. But this test is quite complex (it pushes strings on hooks into array and then compares those to predefined referene) and I had no time to dig, so I just left the check.
I've just took a look at it and the only difference is that for ```pop()``ing non-initialized value:
- currently we: call ```afterCreate```, then call ```afterAttach```
- after stripping ```storedValue``` check - ```afterAttach``` is not called at all.

**Comment by k-g-a** [comment]
BTW, we do not call beforeDetach for ```pop()```ing, which seems like a bug?

**Comment by k-g-a** [comment]
Just made a quick debug to find out whats going on. We ```die()``` pop'ed node during reconcilation, but then initialize it back. I propose merging this PR to fix the issue. Later on I will look closer and make a separate PR if needed.

**Comment by xaviergonz** [comment]
@k-g-a you lost me there :) I'm ok with waiting if there's a possibly better fix.

**Comment by xaviergonz** [comment]
as suggested by @k-g-a I'll merge this until a possibly better fix is found

PS: maybe pop is not calling beforeDetach but it is calling beforeDestroy?
I'd say that's the right thing to do since strictly speaking the node is being "removed" from the tree

Note: I did not check if that's the case or not

**Pull request merged**
