### PR TITLE
Add setImmediateWithFallback util

### PR DESCRIPTION
**Pull request by isaachinman**
@mweststrate Let me know if you want test coverage. Also, you specifically requested `setTimeout(fn, 1)`, but I think a value of zero would do just as well in this case, no?

### CODE REVIEW

**Comment by xaviergonz** [comment]
Looks good to me, just I'm not sure why settimeout is set to 1 instead of 0

**Comment by mweststrate** [comment]
IIRC it doesn't matter, anything below 5 defaults to 5 in most browsers.

**Comment by mweststrate** [comment]
LGTM, thanks for investigating this!

**Comment by mweststrate** [comment]
Released in 3.16.0.

**Comment by wscotten** [comment]
@mweststrate awesome!  Thank you so much!!!!

**Pull request merged**
