### PR TITLE
Add experimental union & compose type helpers

### PR DESCRIPTION
**Pull request by Bnaya**
Following lessons learned in
https://github.com/mobxjs/mobx-state-tree/issues/1425#issuecomment-558008891

### CODE REVIEW

**Comment by mweststrate** [comment]
LGTM at first sight. Do you know any downsides of this approach? If you don't know about any, and not tests fail, I'd just make it the standard rather than creating an alternative API :)

I expect btw with the upcoming variadic tuples, quite some overloads of other api's can be cleaned up as well: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#variadic-tuple-types

**Comment by Bnaya** [comment]
I will give it more time in the weekend!

**Comment by arodik** [comment]
@Bnaya that's awesome! Уou did great work! Are you going to finish it? I think that all MST devs will be grateful

**Comment by Bnaya** [comment]
> @Bnaya that's awesome! Уou did great work! Are you going to finish it? I think that all MST devs will be grateful

I've found some issues with it, that i'm not sure I could make a version fit for general use.
But it's a simple wrapper function around regular union, you may just copy it and use it in your project

**Comment by jamonholmgren** [comment]
@Bnaya Does that mean we should close this PR? Might make sense to put it in the documentation somewhere as a recipe.

**Comment by Bnaya** [comment]
I've closed it for now

**Comment by philllies** [comment]
@Bnaya could you elaborate on the issues you encountered?

**Pull request closed without merging**
