### PR TITLE
Feat/add formatting config

### PR DESCRIPTION
**Pull request by coolsoftwaretyler**
## What does this PR do and why?

Closes https://github.com/mobxjs/mobx-state-tree/issues/2219.

This changes our Prettier config to match the [config for MobX](https://github.com/mobxjs/mobx/blob/main/.prettierrc).

It also runs `bun prettier:write` against the whole codebase, so there's a huge diff here.

We actually have [Husky](https://github.com/typicode/husky) set up to do this as a pre-commit hook already. I think the reason we've had a bunch of diffs is because some of the source files hadn't been given the correct formatting at some point, so as we've made changes throughout the codebase, the Husky hook has formatted them for us.

I've also added a step to run `prettier:check` in CI, so if people skip the hook, we'll see the problem in PRs.

## Steps to validate locally

You should have `[typescript]editor.formatOnSave: true` in `.vscode/settings.json`. Turn that to `false`, then make a change to a file that breaks the Prettier config.

Save the file, add it, and commit it. Husky should clean up your code. 

`bun test` should pass, and `bun run build` should pass and work.

CI should pass on this branch, including the new `check-prettier` job.

### CODE REVIEW

**Comment by coolsoftwaretyler** [comment]
Hey @thegedge - whaddya think? I think we've actually had this in place, but the starting point for all our files was off, so it looked like it was broken.

This adopts MobX's style, and also sets up a CI job to check Prettier on PRs.

I notice we're still on TSLint which [has been deprecated for five years lol](https://palantir.github.io/tslint/). I'm gonna open a separate issue to move to ESLint and its TypeScript tooling.

**Comment by thegedge** [comment]
🙌 🎉 

I checked out this branch, saved a file, and it still had changes. Seems like a couple of things:

1. I have things set up, globally, to organize imports. Not sure if we're deviating from mobx here, but I really like having imports sorted and organized (and it removes unused ones too!). What do you think of including https://www.npmjs.com/package/prettier-plugin-organize-imports? Otherwise, I can just turn this off for MST :)
2. Ternaries are formatting differently for me (see screenshot, `src/core/mst-operations.ts`)

CleanShot 2024-11-27 at 16 27 18@2x

**Comment by coolsoftwaretyler** [comment]
Hey @thegedge - I like that import organizing rule as well. Since you're one of the top contributors these days, let's slightly deviate from MobX on this one so you don't need to make any changes yourself. I think that's pretty fair.

I also like removing unused imports automatically. That's a big selling point for me.

I can't reproduce your ternary issue. Any chance that's some other global config overriding the project? This is what I see with format-on-save:


https://github.com/user-attachments/assets/a3aed3da-0f25-43b3-ae20-2d2c24843b36

And if I turn off format-on-save and run `yarn prettier:write`:

https://github.com/user-attachments/assets/27615d1a-eb74-4f62-a9f0-7b1af77808ca

**Comment by coolsoftwaretyler** [comment]
Oh dang, there's some kind of funky import order dependency here that's failing a bunch of tests. I might be inclined to actually drop that commit and just go with the MobX defaults, rather than wrestle with these weird types for now.

If we cut a new branch for bigger rewrite/refactoring, we could turn that plugin on for that endeavor and try to avoid whatever import magic is going on right now.

**Comment by thegedge** [comment]
> I can't reproduce your ternary issue. Any chance that's some other global config overriding the project? This is what I see with format-on-save:

Maybe! I'll double check sometime this week, but feel free to not wait for me. Happy to ship as-is!

**Comment by coolsoftwaretyler** [comment]
Sweet. Shippin it!

**Pull request merged**
