### PR TITLE
fix undoManager grouping for arrays etc.

### LINKED ISSUE #754: UndoManager - startGroup not working corretly [mst-middlewares]
Hi, I have been speaking with @robinfehr and we have detected a bug with the startGroup.

>  the reverse patches aren't the reverse patches but the normal patches

https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mst-middlewares/src/undo-manager.ts#L73

In this case, the UndoManager undo method is not working fine after this:

code

Thanks!!

### PR DESCRIPTION
**Pull request by robinfehr**
fixes #754

### CODE REVIEW

**Comment by robinfehr** [comment]
currently you’d have to checkout the branch. then

‘’’
yarn 
yarn build
‘’’

goto your project

‘’’
rm -rf node_modules/mst-middlewares
npm install ../../mobx-state-tree/packages/mst-middlewares
‘’’ 

sent from the phone so beware of the mistakes :)

**Comment by mweststrate** [comment]
Looking good, merged

**Comment by chemitaxis** [comment]
Thanks @mweststrate Do you know when we could have this fix in a new release?

**Comment by mweststrate** [comment]
Will cut a release once https://travis-ci.org/mobxjs/mobx-state-tree is
green

Op do 5 apr. 2018 om 15:52 schreef Chema <notifications@github.com>:

**Comment by chemitaxis** [comment]
Nice! It's green right now! ;)

**Comment by mweststrate** [comment]
Done

Op do 5 apr. 2018 om 16:17 schreef Chema <notifications@github.com>:

**Pull request merged**
