### PR TITLE
fix : API description

### PR DESCRIPTION
**Pull request by uufish**
Can I call a constructor?

```js
// const todo = new Todo()
const todo = Todo.create()
unprotect(todo)
todo.done = true // OK
protect(todo)
todo.done = false // throws!
todo.toggle() // OK
```

### CODE REVIEW

**Comment by cpunion** [comment]
Please don't commit the `.idea` directory.

**Comment by uufish** [comment]
I'm sorry.

**Comment by mweststrate** [comment]
Will you create a new PR? The change itself was correct 😊

Op vr 30 jun. 2017 10:55 schreef uufish <notifications@github.com>:

**Comment by uufish** [comment]
Thank you. (  ' - ')ノ

**Pull request closed without merging**
