### PR TITLE
Enable Production Development Error Message

### PR DESCRIPTION
**Pull request by OverseePublic**
https://github.com/mobxjs/mobx-state-tree/pull/1332

### CODE REVIEW

**Comment by xaviergonz** [comment]
Looks good, though there should be something on the readme explaining this

**Comment by xaviergonz** [comment]
Actually I think it would be better to create a new typeCheckingEnabled() function that uses that code and move only the type checking stuff from using devMode() to that new one and leaving devMode as is, since devMode for example also enables stuff unrelated to type checking such as freezing objects and the like

**Comment by OverseePublic** [comment]
> Actually I think it would be better to create a new typeCheckingEnabled() function that uses that code and move only the type checking stuff from using devMode() to that new one and leaving devMode as is, since devMode for example also enables stuff unrelated to type checking such as freezing objects and the like

I made updates to the PR. Could you take a look? Thanks for the comment.

**Comment by OverseePublic** [comment]
@mweststrate or @xaviergonz could one of you approve and allow me to merge this? Thanks.

**Comment by xaviergonz** [comment]
Will check it later today, but so far looks good to me

**Comment by OverseePublic** [comment]
> Will check it later today, but so far looks good to me

@xaviergonz good afternoon. Have you got a chance to look over? Our team is waiting. Thank you

**Comment by mweststrate** [comment]
Merged

**Comment by xaviergonz** [comment]
Just crossed my mind , will this work on environments where process or process. env is not defined?

**Comment by mweststrate** [comment]
good catch, I'll add a guard

**Comment by mweststrate** [comment]
Released as 3.14.1

**Pull request merged**
