### PR TITLE
Add union tips

### LINKED ISSUE #1907: Union types differing only by arrays cause subtle downstream bugs
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

**Sandbox link or minimal reproduction code**

_This builds on https://github.com/mobxjs/mobx-state-tree/discussions/1906_

```
const Foo = types.model({ foo: types.array(types.string) });
const Bar = types.model({ bar: types.array(types.number) });
const FooBar = types.union(Foo, Bar);

const test_foo = { foo: ["test"] };
const test_bar = { bar: [200] };
```

**Describe the expected behavior**
```
it("validates correctly", () => {
  expect(Foo.is(test_foo)).toBeTruthy();
  expect(Bar.is(test_foo)).toBeFalsy();
  expect(Foo.is(test_bar)).toBeFalsy();
  expect(Bar.is(test_bar)).toBeTruthy();
});
```

**Describe the observed behavior**

`toBeFalsy` expectations fail.

---

_This is how the bug manifested for me_:

**Sandbox link or minimal reproduction code**

```
const Store = types.model({ foobars: types.array(FooBar) });

const store = Store.create({
  foobars: [test_foo, test_bar],
});

const foo = store.foobars[0];
const bar = store.foobars[1];
```

**Describe the expected behavior**

```
it("gets correctly", () => {
  expect(foo.foo).toEqual(["test"]);
  expect(foo.bar).toBeUndefined();

  expect(bar.bar).toEqual([200]);
  expect(bar.foo).toBeUndefined();
});
```

**Describe the observed behavior**

`bar.bar` is `undefined`, `bar.foo` is `[]`

---

I'm able to work around it buy putting `type: types.literal("foo")` and `type: types.literal("bar")` on the models,
but it would be nice if MST could let the user know that there are ambiguous union types.
(especially when union types which differ by _something other than an array_ seem to work automagically, per https://github.com/mobxjs/mobx-state-tree/discussions/1906)

### PR DESCRIPTION
**Pull request by chakrihacker**
## What does this PR do and why?

Add Docs about union bugs and how to write better union types

## Steps to validate locally

Not necessary

closes #1907

### CODE REVIEW

**Comment by chakrihacker** [comment]
closes #1907

**Review by chakravarthi-bb — COMMENTED** [review]
Can you also fix `map.test.ts` there's this test case `numeric keys should work` which contains typescript `as any` please remove it and make the test pass

**Comment by coolsoftwaretyler** [comment]
Hey @chakravarthi-bb - I'm sorry I didn't see this before. I've been really busy at work + I don't seem to get notifications for PRs in this repo? I'm going to turn on my notifications + get around to reviewing this after we ship 5.2.0. Sorry to leave you hanging there, but thank you for the PR!

**Comment by coolsoftwaretyler** [comment]
Looks great, @chakrihacker! I'm going to merge this in now. It'll hit the docs page once we do another release and update that.

I think right now our docs are a little too coupled to our versioning, which can be a bit of a pain. If we want to ship it faster, we could release a patch version that ships this specifically.

Either way, this is good to merge. Thank you!

**Comment by chakrihacker** [comment]
Thanks for merging this

**Pull request merged**
