### PR TITLE
Docs for mst-query

### PR DESCRIPTION
**Pull request by k-ode**
This is just a draft pr to track my work on creating docs for mst-query. 

Feel free to leave comments!

### CODE REVIEW

**Comment by coolsoftwaretyler** [comment]
Thanks @k-ode! Let me know when you're ready for review.

If you get a chance, will you please consider adding this in the "recipes" section, rather than the tips? I think these sort of extra ecosystem tools make sense in the format of "what problem did I need to solve, and here's how I solved it"

**Comment by k-ode** [comment]
@coolsoftwaretyler This took a while 😅 But it's ready for review now.

**Comment by coolsoftwaretyler** [comment]
Thanks @k-ode! I'll take a look soon. Really appreciate your time here.

**Review by coolsoftwaretyler — CHANGES_REQUESTED** [review]
@k-ode - this is phenomenal!

The only thing we're missing is a link to mst-query. Should we link to:

1. The GitHub: https://github.com/ConrabOpto/mst-query
2. npm: https://www.npmjs.com/package/mst-query
3. Somewhere else? 

Let me know, then we can add that and ship this to the docs site!

**Comment by k-ode** [comment]
@coolsoftwaretyler I added a link to GitHub.

**Comment by coolsoftwaretyler** [comment]
Updated the title to be a little clearer, but other than that I think we're good to go. Will merge and deploy. Thanks so much, @k-ode! Feel free to submit additional PRs if you ever need to want things up to date.

**Pull request merged**
