### PR TITLE
Loosen model name check

### LINKED ISSUE #1349: ModelType.name check seems too strict
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [ ] I tried the [spectrum channel](https://spectrum.chat/?t=dad48299-3dfc-4e10-b6da-9af1e39498a3)

There is a suspicious check for model name at ModelType:
```ts
// TODO: this test still needed?
if (!/^\w[\w\d_]*$/.test(name))
  throw fail$1("Typename should be a valid identifier: " + name);
```

We're trying to use scoped model names, i.e. ```MyModel@82d92470-d05e-4dab-92cc-25b45f7fa2e4```, which do not pass the check mentioned above, but is valid for most operations in js (can be used as a key for object or as identifier attribute for dom elements). I can't think of any reason for such a strict check.

I propose either loose the check or remove it completely. Can make a PR.

### PR DESCRIPTION
**Pull request by k-g-a**
Fixes #1349. As the question is unanswered I did not dare to remove it completely.

### CODE REVIEW

**Comment by xaviergonz** [comment]
did you try if the tests pass when removing the whole limit? I can't think of a reason of why it couldn't just be any kind of string

**Comment by k-g-a** [comment]
Nope. Will give it a shot tomorrow :)

**Comment by k-g-a** [comment]
Well, all the tests pass without model name check, so i've removed it completely

**Comment by xaviergonz** [comment]
in it goes

**Pull request merged**
