### PR TITLE
Lerna MonoRepo

### PR DESCRIPTION
**Pull request by mattiamanzati**
As discussed with @mweststrate , this PR initializes a lerna monorepo.
This way we can easily make examples depend on mobx-state-tree itself, and move eventually middlewares to a separate package that will be compiled and bundled.

### CODE REVIEW

**Comment by mattiamanzati** [comment]
@mweststrate Is it fine for you to have all the middleware as separate packages like mst-middleware-redux, etc... or do you prefer a single package, mst-middlewares with all the middlewares?

**Comment by mattiamanzati** [comment]
Pro of the new setup: building the library also builds the examples and run test over them, so if any change breaks an example, it needs to be updated to make CI happy.

**Comment by mattiamanzati** [comment]
@mweststrate Should be done now, feel free to merge whenever you want :)

**Comment by skellock** [comment]
2 more and I can build a card game.

**Comment by mattiamanzati** [comment]
@skellock LOL
Not sure why all of those errors where'nt running on my machine :/ Some of them appeared only in CI

**Comment by mattiamanzati** [comment]
Going to merge right now, cross your finger everyone! :)

**Pull request merged**
