### PR TITLE
dev-mode only checks

### LINKED ISSUE #275: Type refinement not checked on action (but checked on applySnapshot)
Hi everybody :)

## Summary
We have some weird behaviour about `identifier` checking : 
 - it works well with `applySnapshot`
 - it seems bypassed with an action.

## Context
We have this helper to declare identifiers :
```es6
export default (name: string) => types.identifier(
  types.refinement(
    'id',
    types.string, identifier => identifier.indexOf(`${name}_`) === 0,
  ),
)
```

We have this model (Author): 
```es6
import { types } from 'mobx-state-tree'
import { getIdType } from './helpers'

const name: string = 'Author'

export default types.model(
  name,
  {
    id: getIdType(name),
    name: types.string,
    image: 'https://cdn.pixabay.com/photo/2016/11/18/23/38/child-1837375_1280.png',
  },
)
```

## Error
Using an action to set our store: the `Author` identifier is not checked. 😢 
Using `applySnapshot`: the `Author` identifier is checked. 👍 

----

## With an action
image

## With `applySnapshot`
PR: https://github.com/fabienjuif/gni-mst/pull/4/files
```es6
`AnonymousModel`:
at path "/recipes/0/author/id" value `"char_1"` is not assignable to type: `identifier(id)`, expected an instance of `identifier(id)` or a snapshot like `identifier(id)` instead.
```

## With `applySnapshot` fix
PR: https://github.com/fabienjuif/gni-mst/pull/5/files
image

### PR DESCRIPTION
**Pull request by mattiamanzati**
- [X] introduce checks for all the top-level types definitions
- [x] introduce checks for all top-level MST utility functions
- [X] run type-checks only in dev-mode
- [X] fixed #275 

cc @mweststrate

### CODE REVIEW

**Comment by mweststrate** [comment]
Impressive! Is the goal:

1. smaller prod builds?
2. runtime perfromance?
3. both :)?

Also, could `process.env.NODE_ENV !== "production"` be rewritten to some `const isProduction` in `utils`, or would that kill the minification?

**Comment by mattiamanzati** [comment]
Main goal is DX, I discovered through user issues that the lack of call checks resulted in weird issue when the user make mistakes. This aims to make the DX better by throwing whenever something is calling not in the correct way! :)
Some checks have been moved to be dev-only, so yeah, will definetely result in smaller build for production :)
I need to re-check that, slept on it and figured out why the first time i've done that it did'nt worked out.

**Comment by mattiamanzati** [comment]
Nope, tried out declaring a global __DEV__, but ends up not being removed in prod build :/

**Comment by mattiamanzati** [comment]
@mweststrate Can I merge this or do you prefer to first merge your others PR and then merge this since this may break the other PRs? :)

**Comment by mweststrate** [comment]
LGTM, feel free to merge. But I think the readme might give some attention how to set it up properly :) (at least for webpack builds, which is probably the most common)

**Comment by mattiamanzati** [comment]
Added to the readme on the tips section, if build passes, I'll merge to master :)

**Pull request merged**
