### PR TITLE
Reimplement `STNValue`, fixes regression issue

### LINKED ISSUE #1307: Issues with Typescript 3.5.1 release
Typescript 3.5.1 just got released. After upgrading from typescript@3.5.0-dev.20190512 the following no longer seems to be working:

```
import { types, IAnyType } from "mobx-state-tree";

export const createCustomType = <ICustomType extends IAnyType>({
  CustomType
}: {
  CustomType: ICustomType;
}) => {
  return types
    .model("Example", {
      someProp: types.boolean,
      someType: CustomType
    })
    .views(self => ({
      get isSomePropTrue(): boolean {
        return self.someProp;
      }
    }));
};

```

Here is the complete error:

```
Property 'someProp' does not exist on type 'STNValue<ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{ someProp: ISimpleType<boolean>; someType: ICustomType; }>>, IModelType<ModelPropertiesDeclarationToProperties<{ someProp: ISimpleType<boolean>; someType: ICustomType; }>, {}, _NotCustomized, _NotCustomized>>'.
  Property 'someProp' does not exist on type 'Exclude<ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{ someProp: ISimpleType<boolean>; someType: ICustomType; }>>, object>'.ts(2339)
```

Are the typings of MST compatible with TS 3.5.1?

When hovering over `self` of `.views(self => ({`. In TS 3.4.3 it was:
```
(parameter) self: ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{
    someProp: ISimpleType<boolean>;
    someType: ICustomType;
}>> & IStateTreeNode<IModelType<ModelPropertiesDeclarationToProperties<{
    someProp: ISimpleType<boolean>;
    someType: ICustomType;
}>, {}, _NotCustomized, _NotCustomized>>
```

While in TS 3.5.1 `self` of `.views(self => ({` seems to be:
```
(parameter) self: STNValue<ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{
    someProp: ISimpleType<boolean>;
    someType: ICustomType;
}>>, IModelType<ModelPropertiesDeclarationToProperties<{
    someProp: ISimpleType<boolean>;
    someType: ICustomType;
}>, {}, _NotCustomized, _NotCustomized>>
```

I tracked down that thing started breaking since typescript@3.5.0-dev.20190514. typescript@3.5.0-dev.20190512  was still fine.

### PR DESCRIPTION
**Pull request by mweststrate**
Should fix #1307

### CODE REVIEW

**Comment by xaviergonz** [comment]
I can confirm that the fix is good :)
```
type A = STNValue<{ x: number } | number | undefined, IType<number, number, number>>


type A = number | ({
    x: number;
} & IStateTreeNode<IType<number, number, number>>) | undefined
```

**Comment by mweststrate** [comment]
Awesome, thanks! I'll release it!

**Comment by sisp** [comment]
I believe this fix has introduced a new bug with TS 3.5: https://codesandbox.io/s/objective-cdn-qdtpt

```
(parameter) self: STNValue<ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{
    kind: ISimpleType<K>;
} & T>>, IModelType<ModelPropertiesDeclarationToProperties<{
    kind: ISimpleType<K>;
} & T>, {}, _NotCustomized, _NotCustomized>>
Argument of type 'STNValue<ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{ kind: ISimpleType<K>; } & T>>, IModelType<ModelPropertiesDeclarationToProperties<{ kind: ISimpleType<K>; } & T>, {}, _NotCustomized, _NotCustomized>>' is not assignable to parameter of type 'IAnyStateTreeNode'.
  Type 'ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{ kind: ISimpleType<K>; } & T>> | (ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{ kind: ISimpleType<K>; } & T>> & IStateTreeNode<...>)' is not assignable to type 'IAnyStateTreeNode'.
    Type 'ModelInstanceTypeProps<ModelPropertiesDeclarationToProperties<{ kind: ISimpleType<K>; } & T>>' has no properties in common with type 'IAnyStateTreeNode'.ts(2345)
```

**Comment by mweststrate** [comment]
@sisp please open a new issue or PR. Comments on old PRs / issues are typically  not noticed.

**Pull request merged**
