### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EricForgy**
Was getting syntax errors.

### CODE REVIEW

**Comment by EricForgy** [comment]
Still can't run the Readme example. Now it can't find `action` 🤔

**Comment by mattiamanzati** [comment]
Action is not needed anynore, you van simply pass in the function :)

**Comment by EricForgy** [comment]
Any suggestions how to get the README example to work? I'll gladly try to revise the README once I understand it :)

**Comment by EricForgy** [comment]
Sorry. I'll submit a cleaner PR with some suggestions for README.

**Pull request closed without merging**
