### PR TITLE
fix for references to objects being broken after replacing the node

### LINKED ISSUE #1052: Reference returns destroyed model after subtree replacing
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure your project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/jlnmjqr7xv) code sandbox or another minimal reproduction. 
* https://codesandbox.io/s/lx003ww20m

**Describe the observed behavior**
If we have reference to the some part of subtree and replacing that subtree completely, reference still points to old, destroyed, model, so reference's read/write leads to livelyness error, even if new subtree contains correct new model with same type/identifier as in old model.

There is workaround - in action we can save id from reference in temporary variable, set reference to undefined and after replacing reassign identidier (`Safe reload` button in example). I think, it should be done by library, not by user. Of course, user still needs check if new subtree contains referenced identifier.

**Describe the expected behavior**
Reference should check if model was removed from current tree and return new model with same type/identifier or throw `Failed to resolve reference` if there is no that model in the tree.

### PR DESCRIPTION
**Pull request by xaviergonz**
Fixes #1052

### CODE REVIEW

**Comment by Amareis** [comment]
Does you completely disable optimization with "object" mode in StoredReference?

**Comment by xaviergonz** [comment]
it wasn't much of an optimization given there is an identifier cache underneath that keeps a pointer to the node

**Comment by xaviergonz** [comment]
Also, at first I tried to keep it, but apparently making a mutation (in this case of the ref object) in the middle of a read operation (getValue) makes the system go nuts

**Comment by xaviergonz** [comment]
Btw, the define a property when a property is set in another "this" is basically how JS does things normally internally.
From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
```
Setting a property to an object creates an own property. The only exception to the getting and setting behavior rules is when there is an inherited property with a getter or a setter.
```

**Comment by xaviergonz** [comment]
@k-g-a thanks for the review! all requested changes done :)

**Comment by mweststrate** [comment]
Feel free to release :-)

**Comment by mweststrate** [comment]
I think given the docs one would already assume this to work, so patch
should be ok?

Op di 23 okt. 2018 om 13:27 schreef Javier Gonzalez <
notifications@github.com>:

**Pull request merged**
