### PR TITLE
Case sensitive links in README

### PR DESCRIPTION
**Pull request by seivan**

### CODE REVIEW

**Comment by mattiamanzati** [comment]
Hi! Thanks for your PR! I see API.md named with uppercases, and changing it to lowercase breaks the link, does the same for you?

**Comment by seivan** [comment]
Links to files are case sensitive, yes.

**Comment by mattiamanzati** [comment]
So why the PR changes the link to be lowercase if the file is uppercase?

**Comment by seivan** [comment]
This PR is changing it to uppercase unless I've missed something significant here.

**Comment by mattiamanzati** [comment]
Uh, right. LOL. I just derped, thanks! :)

**Comment by seivan** [comment]
Yeah that was a significant derp. I'm on mobile so I wasn't sure if Githubs shitty mobile UI was derping or you. Thanks.

**Pull request merged**
