### PR TITLE
Allow setting a parent node if the child and parent envs are the same.

### LINKED ISSUE #354: Do not throw if given environment is the same as the target one
Is there any reason why I can't do something like this if the two environments passed on create are the same ones?

```js
const env = whatever;
const parent = Parent.create({}, env);
const child = Child.create({}, env);
parent.children.set('asdf', child); // exception
parent.children.set('asdf', getSnapshot(child)); // ugly workaround, but works
```

I'd understand the error if the two envs were not the same, but when they are?

### PR DESCRIPTION
**Pull request by xaviergonz**
Fixes #354

### CODE REVIEW

**Comment by mattiamanzati** [comment]
@xaviergonz Thanks a lot for this PR!
Could you please add also a test for not throwing if env is === same? :)

**Comment by xaviergonz** [comment]
@mattiamanzati there you go!

**Comment by xaviergonz** [comment]
anything else needed?

**Comment by mattiamanzati** [comment]
I think just the approval of @mweststrate :)

**Comment by mweststrate** [comment]
@xaviergonz approved! Thanks :)

**Pull request merged**
