### PR TITLE
use interfaces wherever possible, they compile/parse faster

### PR DESCRIPTION
**Pull request by xaviergonz**
this small pull request is to change some types to interfaces wherever possible, since they are compiled/parsed faster by TS

### CODE REVIEW

**Comment by xaviergonz** [comment]
while at it also converted the last tests files that were in js to ts

**Comment by mweststrate** [comment]
@xaviergonz ok, let me know when you are comfortable with the changes!

**Comment by xaviergonz** [comment]
that should be it 👌

**Comment by mweststrate** [comment]
Thanks!

**Pull request merged**
