### PR TITLE
Add flag to determine if an action is a flow based action

### PR DESCRIPTION
**Pull request by Slooowpoke**
I was working on some integrations and I found a need to know whether an action was wrapped in flow. It feels like it might be specific to my use case, but equally, it didn't seem like it would cause much bother and might help others?

It's quite a simple PR, just adding `_isFlowAction` to flow based functions and using that in the reflection properties.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
This looks good to me @Slooowpoke! Could you resolve conflicts & then I'll release a new version.

**Comment by jamonholmgren** [comment]
I fixed the conflicts @Slooowpoke -- would you be able to add some documentation for this?

**Comment by jamonholmgren** [comment]
Just waiting on docs.

**Comment by Slooowpoke** [comment]
Sorry, I completely forgot about this, thank you for fixing the conflicts I'll write something later today

**Comment by coolsoftwaretyler** [comment]
Hey @Slooowpoke - any update on the docs here?

If you don't have the time or energy, I'm happy to take that on and get this merged, although I'd love maybe a short bulleted list about these changes to start from.

**Comment by coolsoftwaretyler** [comment]
Having not heard back, I'm going to assign myself and see if I can put together some docs for this.

**Comment by coolsoftwaretyler** [comment]
Hey @jamonholmgren - I [updated the docs for this PR](https://github.com/mobxjs/mobx-state-tree/pull/1856/commits/c1d1577fe3c41029779da3cfe3c626d9f4bfcbcb), to the best of my understand of what's changed here.

@Slooowpoke - if you end up seeing this in the near future, let me know if there's any modifications you'd make to my docs here. I think I understood the changes correctly. Would love to get this PR merged for y'all, I know it's been a while.

**Comment by coolsoftwaretyler** [comment]
After messing around on a separate branch, I [figured I should run `yarn build-docs`](https://github.com/mobxjs/mobx-state-tree/pull/1856/commits/4b6d6a1090cdd813dc79a4a9da46605f87176722) as well, but I'm not exactly sure if that's required for the PR, or if we do that in a separate process elsewhere.

**Review by jamonholmgren — APPROVED** [review]

**Pull request merged**
