### PR TITLE
fix: add checks while creating model

### LINKED ISSUE #1725: TypeError: adm.raw is not a function in React Native with TypeScript
**_Question_**

* [x] I've checked documentation and searched for existing issues
* [x] I tried [GitHub Discussions](https://github.com/mobxjs/mobx-state-tree/discussions)

Hi, when trying to add mobx state tree with mobx react lite to a React Native CLI empty project (generated with cra) with TypeScript I'm getting a runtime error after an app started with the message `TypeError: adm.raw is not a function. (In 'adm.raw()', 'adm.raw' is undefined)`. Full error log is below:  
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: adm.raw is not a function. (In 'adm.raw()', 'adm.raw' is undefined)
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:123654:32
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:123642:38
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:123773:20
forEach@[native code]
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:123772:35
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:123641:25
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119688:77
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119762:53
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119044:26
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119758:34
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119470:30
executeAction@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113471:22
res@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113451:27
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:119405:42
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:120289:46
get@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:118895:34
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:120178:65
executeAction@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113471:22
res@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113451:27
value@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:120281:44
executeAction@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113471:22
res@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:113451:27
setupAppStore$@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:117958:49
tryCatch@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:28650:23
invoke@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:28823:32
tryCatch@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:28650:23
invoke@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:28723:30
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:28733:21
tryCallOne@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:3419:16
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:3520:27
_callTimer@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:30679:17
_callImmediatesPass@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:30718:17
callImmediates@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:30935:33
__callImmediates@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:2707:35
http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:2493:34
__guard@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:2690:15
flushedQueue@http://10.0.1.120:8081/index.bundle?platform=ios&dev=true&minify=false:2492:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]
```
 This is how my dependencies look's like: 
```
 "dependencies": {
    "mobx": "5.15.7",
    "mobx-react-lite": "2.2.2",
    "mobx-state-tree": "^5.0.1",
    "react": "16.13.1",
    "react-native": "0.63.3",
     ...
  },
```
It's my root store: 
```
import {types, Instance} from 'mobx-state-tree';

const RootStore = types
  .model('RootStore', {
    isReady: types.optional(types.boolean, false),
  })
  .actions((self) => {
    return {
      setReady(booleanState: boolean) {
        self.isReady = booleanState;
      },
    };
  });

export type RootStoreModel = Instance<typeof RootStore>;
export default RootStore;
```
My setupRootStore method: 
```
const setupRootStore = async (): Promise<RootStoreModel> => {
  const env = await createEnvironment();
  return RootStore.create({}, env);
};
```
This is how I create Context: 
```
const StoreContext = createContext<RootStoreModel>({} as RootStoreModel);
```
And my entry point `App.tsx` where I initialise the store and provide the context looks like this: 
```
const App: React.FC = () => {
 const [rootStore, setRootStore] = useState<RootStoreModel | null>(null);

  useEffect(() => {
    (async () => {
      setRootStore(await setupRootStore());
    })();
  }, []);

  if (!rootStore) return null;

  return (
    <StoreContext.Provider value={rootStore}>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView>
          <Welcome />
        </ScrollView>
      </SafeAreaView>
    </StoreContext.Provider>
  );
}
```

What could cause such an error? Am I missing something? 
Thank you in advance for your answers

### PR DESCRIPTION
**Pull request by chakrihacker**
closes #1725 

closes https://github.com/mobxjs/mobx-state-tree/issues/1537

### CODE REVIEW

**Comment by chakrihacker** [comment]
@coolsoftwaretyler I am not able to add you as reviewer, Can you please check this??

**Comment by coolsoftwaretyler** [comment]
@chakrihacker - sure thing. Will you please add a description to this PR and link to any relevant issue(s)?

**Comment by coolsoftwaretyler** [comment]
Thanks @chakrihacker! I will take a look sometime this week or over the weekend.

**Comment by coolsoftwaretyler** [comment]
I think this also closes out https://github.com/mobxjs/mobx-state-tree/issues/1537 - edited description as such.

**Comment by coolsoftwaretyler** [comment]
Looks great! Thanks @chakrihacker. I'll get this in a patch release sometime soon.

**Pull request merged**
