### PR TITLE
fix broken links in README.md

### PR DESCRIPTION
**Pull request by ArturJS**
Some links in README.md seemed to be broken.
Let me know if there is anything else that should also be included in this PR.

### CODE REVIEW

**Comment by ArturJS** [comment]
Hmm, some tests were failed.
@mweststrate Would it be ok if I add fix for them as a part of this PR?

**Comment by mweststrate** [comment]
Thanks for looking into this! For the intro we can probably best link to https://mobx-state-tree.js.org/intro/getting-started now. 

Good catch about the tests! They are most probably failing because a filepath is wrong, as they check if all methods are documented in the api overview .md file

**Comment by ArturJS** [comment]
@mweststrate Done.

**Comment by mweststrate** [comment]
Awesome, thanks @ArturJS (& @auvipy)!

**Pull request merged**
