### PR TITLE
Enable clear the UndoManager and callbacks in undo()/redo() actions

### LINKED ISSUE #1107: Enable clear the UndoManager and callbacks in undo()/redo() actions
**_Feature request_**
Enable clear the UndoManager and callbacks in undo()/redo() actions

**Is your feature request related to a problem? Please describe.**
It's not a problem, it's a feature to implement.

**Describe the solution you'd like**
I have implemented

**Describe alternatives you've considered**
Overwrite the UndoManager.

**Additional context**

Sometimes you would need to clear the UndoManager, for example, an error. Sometimes you need to execute a custom callback function after you can redo()/undo() actions

**Are you willing to (attempt) a PR?**
* [X ] Yes
* [ ] No

### PR DESCRIPTION
**Pull request by chemitaxis**
Hi @mweststrate and @robinfehr please look at this:

Closes #1107

### CODE REVIEW

**Comment by xaviergonz** [comment]
@chemitaxis thanks for your work! One last thing before it is merged, could you update the changelog file? Thanks!

**Comment by chemitaxis** [comment]
Hi! What will be the correct version of the next release? Thanks!

**Comment by xaviergonz** [comment]
don't worry about that, it depends on the kind of changes made, just put a line on the top with the change definition

**Comment by robinfehr** [comment]
@chemitaxis thx

**Pull request merged**
