### PR TITLE
Use Array.from with .values() in React iteration

### PR DESCRIPTION
**Pull request by luisherranz**
I've also fixed and updated the codesandbox to the latest version of React, Mobx and Mobx-State-Tree.

### CODE REVIEW

**Comment by robinfehr** [comment]
maybe we should directly introduce `values(x)` what do you think?

**Comment by luisherranz** [comment]
So... `import { values } from 'mobx'` or `import { values } from 'mobx-state-tree'`?

**Comment by robinfehr** [comment]
what I've meant was more if we already should show the newcomers to the `values(x)` from mobx instead of making them use the `Array.from` option. 

adding the same to mst that is in mobx already...idk, I think the users have to get used to use both anyway.

**Comment by mweststrate** [comment]
Just from mobx

Op do 26 apr. 2018 12:14 schreef Rob <notifications@github.com>:

**Comment by luisherranz** [comment]
done!

**Comment by mweststrate** [comment]
Thanks!

**Pull request merged**
