### PR TITLE
Enable typechecking

### PR DESCRIPTION
**Pull request by OverseePublic**
https://github.com/mobxjs/mobx-state-tree/issues/1304

### CODE REVIEW

**Comment by OverseePublic** [comment]
@mweststrate so seems like the approach you suggested was not acceptable in MobX repository... how about we go through ENV route and figure out the configuration object later?

https://github.com/mobxjs/mobx-state-tree/pull/1337

**Comment by xaviergonz** [comment]
I'd close this in favor of the other PR, mobx shouldn't have to change to accommodate to one of its dependencies requirements

**Comment by xaviergonz** [comment]
Not to mention that this would effectively kill the optimization done by the minimizer in production mode since now it would not be able to remove the dev mode code (since now that flag would depend on a simple variable) 

IOW, closing in favor of the approach in #1337

**Comment by mweststrate** [comment]
Released as 3.14.1

**Pull request closed without merging**
