### PR TITLE
add wallaby.js. fix tests to run with wallaby and "yarn run test"

### PR DESCRIPTION
**Pull request by RainerAtSpirit**
Adding wallaby https://wallabyjs.com/ support. Running `yarn run test` should work as before.
Wallaby has a commercial license model, so using wallaby is purely optional.

### CODE REVIEW

**Comment by RainerAtSpirit** [comment]
travis `npm run coverage` fails. Travis is using an older node 4.x version. Works fine locally on `node 6.10.1`

**Comment by mweststrate** [comment]
feel free to upgrade to node 6 in .travis.ci

**Comment by RainerAtSpirit** [comment]
Upgrading travis to 6.10.1 let the tests pass. Coverage decrease it probably due to me rebasing to the latest.

**Comment by RainerAtSpirit** [comment]
@mweststrate: Had to change the regex in order to make the test pass in wallaby. This might be another reason for the decreased coverage.

https://github.com/mobxjs/mobx-state-tree/commit/9d81940dacb599fbb58ca65ff5c29d9ea708ae68#diff-d6e705a0a3d95d371e5d536e02bd69dcR25

```javascript
 }, /IAmUnserializable(.|\n)* is not assignable to type: frozen/)
```

**Pull request merged**
