### PR TITLE
applyPatch replace root of store if path is empty

### PR DESCRIPTION
**Pull request by epodgaetskiy**
It seems to fix [#1411](https://github.com/mobxjs/mobx-state-tree/issues/1411)
Using the recommendation [replace the entire structure](https://github.com/mobxjs/mobx-state-tree/issues/1411#issuecomment-547102748)

### CODE REVIEW

**Comment by jamonholmgren** [comment]
@epodgaetskiy I'm taking over as primary maintainer on MST. What's the status on this PR? Still feel like it should be pushed through? Looks like there are some conflicts.

**Comment by epodgaetskiy** [comment]
@jamonholmgren Fixed conflicts.

**Comment by epodgaetskiy** [comment]
@jamonholmgren PR is ready for merge

**Review by jamonholmgren — APPROVED** [review]
Thanks @epodgaetskiy ! Really appreciate it.

**Comment by jamonholmgren** [comment]
We will actually wait for next major version since this could be a breaking change.

**Comment by jamonholmgren** [comment]
https://github.com/mobxjs/mobx-state-tree/releases/tag/v5.0.0

**Pull request merged**
