### PR TITLE
fix(union): Union.create() shouldn't ignore extra arguments

### PR DESCRIPTION
**Pull request by abruzzihraig**
Children in type Union could be any type, currently means it could be either `SimpleType` or `ComplexType` so the rest arguments such as `environment, parent, subpath` shouldn't be ignored in method `Union.create()`.

I would have tried to declare the method `create` into the type `IComplexType` such as:
```
export interface IComplexType<S, T> extends IType<S, T & ISnapshottable<S> & IMSTNode> {
    create(snapshot?: S, environment?: any, parent?: MSTAdministration, subpath?: string): T
}
```
Then it might be a type `IComplexType<any, any>|IType<any, any>` or `IComplexType<any, any>|ISimpleType<any, any>` could be used in the Class Union.

But I'm confused with the current structure in MST:
```
IComplexType extends IType
ISimpleType extends IType
Type implements IType
```
So far so good, but why `ComplexType extends Type` rather than `ComplexType extends Type implements IComplexType`? It doesn't make sense to me.

Besides, if I use the union type like `IComplexType<any, any>|IType<any, any>` or `IComplexType<any, any>|ISimpleType<any, any>`, I wouldn't know how to distinguish them in runtime so that I cannot give it a specific assertion.

That's why finally I just changed the parameter declarations in `IType.create()`.

### CODE REVIEW

**Comment by abruzzihraig** [comment]
Link to #134

**Comment by mattiamanzati** [comment]
Hi! Thanks for your PR!
The other parameters doesnt appear in IType because we dont want them to be visible, can you please revert only the IType declaration? :)

**Comment by abruzzihraig** [comment]
@mattiamanzati if I revert the change in IType, the following lines have to be changed by an assertion `as any`:

https://github.com/mobxjs/mobx-state-tree/pull/151/commits#diff-7536e74658295b48b68949f5100a9989R37 
https://github.com/mobxjs/mobx-state-tree/pull/151/commits#diff-7536e74658295b48b68949f5100a9989R45

Is that ok for your code foundation? Using assertion `as any` here seems is not a good way... But currently, we cannot use IComplexType or something else to restrict it.

**Comment by mattiamanzati** [comment]
Its fine for now, soon when all types will be complex by default, that will no more be an issue :)

**Comment by abruzzihraig** [comment]
@mattiamanzati Pls check it again, thanks.

**Comment by mattiamanzati** [comment]
Now its fine! Thanks for your hard work! :)

**Pull request merged**
