### PR TITLE
Fix MST-boxes example

### PR DESCRIPTION
**Pull request by O4epegb**
`react-draggable` was not working correctly with latest React, so I updated its version. Then I decided to update all the packages altogether :) Everything works as expected so far.

### CODE REVIEW

**Comment by O4epegb** [comment]
I don't really know why Travis failed on `mobx-state-tree` packages. Maybe because I updated Jest?

**Comment by mweststrate** [comment]
@O4epegb most likely. Would you mind updating this PR to just updating react-draggable, and optionally update other deps in a separate PR?

**Comment by O4epegb** [comment]
Done, I guess. Travis is fine, example is working too

**Comment by mweststrate** [comment]
Great! Thanks a lot

**Comment by mweststrate** [comment]
Oops, wrong button..

**Pull request merged**
