### PR TITLE
add(undoManager): add timestamp to the object recorder

### PR DESCRIPTION
**Pull request by abruzzihraig**
Just add a timestamp for recorder objects like what I suggested on https://spectrum.chat/?t=d5c82ac2-8259-45ce-a72c-a4503c591604

Could anyone can help me with it? No matter what discussion or code review on this requirement. Thanks!

### CODE REVIEW

**Comment by abruzzihraig** [comment]
I just found the issue #889 seems to have a similar request with me. If there could be any way to extend the recorder object will be better.

**Comment by robinfehr** [comment]
the timestamp might really be something that is useful and makes sense for this particular middleware. 

I'm not entirely happy that one has to store the timestamp but i guess it wouldn't be that memory / storage (if persisted) consumptive either that it should be optional .
@mweststrate what do you think?


about the extending: I can't yet understand where it could be useful and fit the undoManager middleware topic - middleware for time travelling.

**Comment by abruzzihraig** [comment]
@robinfehr Thanks for your reply.

For the extending, yes I don't know where it could be useful as well. I was just thinking if there would be something like timestamp and we are going to add them into the recorder object in the future, which might be better to make the recorder object extendable. I'm not sure about that.

I agree with you on the timestamp. It should be optional. The code I committed it just basically explains the how did I think about the timestamp. You can even see there is a temporary interface extends IPatchRecorder, which should be modified in some formal way. And that's why I need your help and recommendations.

**Comment by robinfehr** [comment]
hm I guess that's ok since it's extended for this middleware but i'll go over the code in more detail and leave notes if necessary. thanks.

**Comment by abruzzihraig** [comment]
@robinfehr when you check the code, please at lease notice these two points:
1. I'm not sure if the `Date.now()` I used follows the browser compatibility that MST requests
2. I remember that this code change might influence the method `addUndoState` because it can be invoked directly from outside by developers, but they might not know that they can pass a timestamp for the recorder object.

**Comment by mweststrate** [comment]
Closing this PR for the lack of a champion / activity / recent need

**Pull request closed without merging**
